# Generated by Django 2.1.7 on 2019-03-13 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0003_auto_20190313_0241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='maestro',
        ),
    ]
