# Generated by Django 2.1.7 on 2019-03-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0005_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='apellido_m',
            new_name='apellido_materno',
        ),
        migrations.RenameField(
            model_name='teacher',
            old_name='apellido_p',
            new_name='apellido_paterno',
        ),
    ]
