# Generated by Django 2.1.7 on 2019-03-13 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0006_auto_20190313_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='maestros/'),
        ),
    ]
