# Generated by Django 2.1.7 on 2019-03-13 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0007_teacher_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='img/maestros/'),
        ),
    ]
