# Generated by Django 2.1.7 on 2019-03-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0009_archivos_procesos'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivos',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='procesos',
            name='actualizado',
            field=models.DateField(auto_now=True),
        ),
    ]
