# Generated by Django 2.1.7 on 2019-03-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0013_auto_20190319_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='notas',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
