# Generated by Django 2.1.7 on 2019-03-28 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0014_proceso_notas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='archivo_proceso',
            field=models.ManyToManyField(to='itic.Archivo', verbose_name='archivos'),
        ),
    ]
