# Generated by Django 2.1.7 on 2019-03-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0015_proceso_archivo_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='archivos',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default=2),
        ),
    ]
