# Generated by Django 2.1.7 on 2019-03-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0016_proceso_archivos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='archivos',
            field=models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default=2, verbose_name='Contiene Archivos'),
        ),
    ]
