# Generated by Django 2.1.7 on 2019-03-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0017_auto_20190329_1345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archivo',
            name='descripcion',
        ),
    ]
