# Generated by Django 2.1.7 on 2019-03-29 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0019_auto_20190329_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proceso',
            name='archivo_proceso',
            field=models.ManyToManyField(blank=True, to='itic.Archivo', verbose_name='archivos'),
        ),
    ]
