# Generated by Django 2.1.7 on 2019-04-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0020_auto_20190329_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='tipo_proceso',
            field=models.IntegerField(choices=[(1, 'Residencias'), (2, 'Servicio')], default=2, verbose_name='Tipo de Proceos'),
        ),
    ]
