# Generated by Django 2.1.7 on 2019-04-02 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0021_proceso_tipo_proceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='proceso',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='proceso',
            name='tipo_proceso',
            field=models.IntegerField(choices=[(1, 'Residencias'), (2, 'Servicio')], default=1, verbose_name='Tipo de Proceos'),
        ),
    ]
