# Generated by Django 2.2 on 2019-04-20 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0023_auto_20190402_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proceso',
            name='archivo_proceso',
        ),
        migrations.DeleteModel(
            name='Archivo',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
    ]
