# Generated by Django 2.2 on 2019-04-30 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0025_auto_20190430_1710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='id',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
