# Generated by Django 2.2.1 on 2019-05-13 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itic', '0027_auto_20190430_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Author', to=settings.AUTH_USER_MODEL),
        ),
    ]
