# Generated by Django 2.2.1 on 2019-05-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itic', '0028_new_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
