# Generated by Django 2.2 on 2019-04-20 03:04

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='files/')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', tinymce.models.HTMLField()),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('archivos', models.IntegerField(choices=[(1, 'Si'), (2, 'No')], default=2, verbose_name='Contiene Archivos')),
                ('tipo_proceso', models.IntegerField(choices=[(1, 'Residencias'), (2, 'Servicio')], default=1, verbose_name='Tipo de Proceos')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('actualizado', models.DateField(auto_now=True)),
                ('archivo_proceso', models.ManyToManyField(blank=True, to='itspa.Archivo', verbose_name='archivos')),
            ],
        ),
    ]
