# Generated by Django 2.2 on 2019-04-29 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itspa', '0003_auto_20190429_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo'),
        ),
    ]
