# Generated by Django 2.2 on 2019-04-29 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itspa', '0004_auto_20190429_0407'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='nombre',
            new_name='titulo',
        ),
    ]
