# Generated by Django 2.2 on 2019-04-29 04:22

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('itspa', '0005_auto_20190429_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='body',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='descripcion',
            field=tinymce.models.HTMLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='itspa.Tag'),
        ),
    ]
