# Generated by Django 2.2 on 2019-04-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itspa', '0007_auto_20190429_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='noticias/'),
        ),
    ]
