# Generated by Django 2.2 on 2019-04-30 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itspa', '0008_noticia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='Usuario', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='tags',
        ),
        migrations.AddField(
            model_name='noticia',
            name='tags',
            field=models.ManyToManyField(to='itspa.Tag', verbose_name='Tags'),
        ),
    ]
